services:
  db:
    image: postgres:16-alpine
    container_name: ping-pong-db
    restart: always
    environment:
      POSTGRES_USER: pingpong_admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: pingpong_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: