services:
  db:
    image: postgres:16-alpine
    container_name: ping-pong-db
    restart: always
    environment:
      POSTGRES_USER: pingpong_admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: pingpong_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: ping-pong-api
    ports:
      - "3000:3000"
    volumes:
      # Sincroniza el código local con el contenedor en tiempo real
      - ./api:/app
      # Evita que la carpeta local de node_modules sobreescriba la del contenedor
      - /app/node_modules
    depends_on:
      - db
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://pingpong_admin:supersecretpassword@db:5432/pingpong_db?schema=public

  client:
    build: ./client
    container_name: ping-pong-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  pg_data:
