// src/constants/localizaciones.ts

export const LOCALIZACIONES_ESPANA = [
  // --- PROVINCIA DE CASTELLÓN ---
  'Castellón de la Plana',
  'Vila-real',
  'Burriana',
  "La Vall d'Uixó",
  'Vinaròs',
  'Benicarló',
  'Almassora',
  'Onda',
  'Benicàssim',
  'Nules',
  "L'Alcora",
  'Oropesa del Mar',
  'Segorbe',
  'Peñíscola',
  'Moncofa',
  'Alcalà de Xivert',
  'Morella',
  'Almenara',
  'Betxí',
  'Torreblanca',

  // --- PROVINCIA DE VALENCIA ---
  'Valencia',
  'Torrent',
  'Gandia',
  'Paterna',
  'Sagunto',
  'Alzira',
  'Mislata',
  'Burjassot',
  'Ontinyent',
  'Aldaia',
  'Manises',
  'Xàtiva',
  'Xirivella',
  'Sueca',
  'Catarroja',
  'Algemesí',
  'Oliva',
  'Quart de Poblet',
  'Paiporta',
  'Alboraya',
  'La Pobla de Vallbona',
  'Llíria',
  'Bétera',
  'Cullera',
  'Moncada',
  'Riba-roja de Túria',
  'Alfafar',
  'Requena',
  'Picassent',
  'Puçol',
  'Silla',
  'Tavernes de la Valldigna',
  "L'Eliana",

  // --- PROVINCIA DE ALICANTE ---
  'Alicante',
  'Elche',
  'Torrevieja',
  'Orihuela',
  'Benidorm',
  'Alcoy',
  'San Vicente del Raspeig',
  'Elda',
  'Dénia',
  'Petrer',
  'Villena',
  'La Vila Joiosa',
  'Santa Pola',
  'Crevillent',
  'El Campello',
  'Xàbia',
  'Novelda',
  'Mutxamel',
  'Ibi',
  "Sant Joan d'Alacant",
  'Altea',
  "L'Alfàs del Pi",
  'Callosa de Segura',
  'Rojales',
  'Guardamar del Segura',

  // --- CAPITALES Y CIUDADES PRINCIPALES DE ESPAÑA ---
  'Madrid',
  'Barcelona',
  'Sevilla',
  'Zaragoza',
  'Málaga',
  'Murcia',
  'Palma de Mallorca',
  'Las Palmas de Gran Canaria',
  'Bilbao',
  'Valladolid',
  'Córdoba',
  'Vigo',
  'Gijón',
  "L'Hospitalet de Llobregat",
  'A Coruña',
  'Vitoria-Gasteiz',
  'Granada',
  'Oviedo',
  'Badalona',
  'Terrassa',
  'Cartagena',
  'Jerez de la Frontera',
  'Sabadell',
  'Móstoles',
  'Santa Cruz de Tenerife',
  'Alcalá de Henares',
  'Pamplona',
  'Almería',
  'Fuenlabrada',
  'Leganés',
  'Donostia-San Sebastián',
  'Getafe',
  'Burgos',
  'Albacete',
  'Santander',
  'Logroño',
  'Badajoz',
  'Huelva',
  'Salamanca',
  'Marbella',
  'Lleida',
  'Tarragona',
  'León',
  'Cádiz',
  'Jaén',
  'Ourense',
  'Algeciras',
].sort(); // El .sort() ordena alfabéticamente toda la lista automáticamente
